# Generated by Django 5.2.3 on 2025-08-19 08:51

import ckeditor.fields
import treks_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0005_blog_image_url_toptrek_image_url_whatsnew_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', validators=[treks_app.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
