# Generated by Django 5.2.3 on 2025-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0006_alter_blog_content_alter_blog_image_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for SEO', max_length=160),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (optional)', max_length=70),
        ),
    ]
